### ISSUE TITLE
三级往后的标题难区分

### ISSUE THREAD

**Issue by Kitsuta-le** [YYHCOPPOLO/BluePrint-From-Tsundoku#1]
https://user-images.githubusercontent.com/88605687/132990140-5b3f197d-2c8e-405b-af65-37aac9993304.png
主题从背景到配色都非常舒服！期待更新！

**Comment by YYHCOPPOLO** [comment]
> https://user-images.githubusercontent.com/88605687/132990140-5b3f197d-2c8e-405b-af65-37aac9993304.png
> 主题从背景到配色都非常舒服！期待更新！

![image](https://user-images.githubusercontent.com/48144208/132990757-49591bf2-dbbc-48d4-a5f5-729e804deaa8.png)
感谢反馈，会进行改进

**Comment by Kitsuta-le** [comment]
> > https://user-images.githubusercontent.com/88605687/132990140-5b3f197d-2c8e-405b-af65-37aac9993304.png
> > 主题从背景到配色都非常舒服！期待更新！
> 
> ![image](https://user-images.githubusercontent.com/48144208/132990757-49591bf2-dbbc-48d4-a5f5-729e804deaa8.png)
> 感谢反馈，会进行改进

嗯嗯，但是我觉得3级到4级辨识度不是很高。。。

**Comment by YYHCOPPOLO** [comment]
> > > https://user-images.githubusercontent.com/88605687/132990140-5b3f197d-2c8e-405b-af65-37aac9993304.png
> > > 主题从背景到配色都非常舒服！期待更新！
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/48144208/132990757-49591bf2-dbbc-48d4-a5f5-729e804deaa8.png)
> > 感谢反馈，会进行改进
> 
> 嗯嗯，但是我觉得3级到4级辨识度不是很高。。。

先凑合一下..暂时没想到啥更好看的方案

**Comment by w753621** [comment]
請問background可以不要有格子線嗎

**Comment by YYHCOPPOLO** [comment]
> 
> 
> 請問background可以不要有格子線嗎

可以的，用txt或者别的编辑器打开主题中的css
然后把下列的内容删掉即可
.b3-typography, .protyle-wysiwyg {

    background-image: linear-gradient(90deg,rgba(60,10,30,.04) 3%,transparent 0),linear-gradient(1turn,rgba(60,10,30,.04) 3%,transparent 0);
    background-size: 20px 20px;
    background-position: 50%;

}

**Comment by w753621** [comment]
the best theme 👍

**Comment by YYHCOPPOLO** [comment]
> the best theme 👍

感谢支持，有任何建议也可以在这里反馈

**Comment by alanjustalan** [comment]
> > the best theme 👍
> 
> 感谢支持，有任何建议也可以在这里反馈

希望主题能持续更新哈，真的挺好看的！

**Comment by YYHCOPPOLO** [comment]
> > > the best theme 👍
> > 
> > 
> > 感谢支持，有任何建议也可以在这里反馈
> 
> 希望主题能持续更新哈，真的挺好看的！

会的会的，最近太忙了，马上要考试了(泪目
