### ISSUE TITLE
右上角的选项键看不到、大纲没有显示线条

### ISSUE THREAD

**Issue by Kitsuta-le** [YYHCOPPOLO/BluePrint-From-Tsundoku#2]
![image](https://user-images.githubusercontent.com/88605687/133281750-851f7fc2-cdb0-460f-bc11-3d9ce6911c02.png)
![image](https://user-images.githubusercontent.com/88605687/133281787-74c6b9fd-142d-4b27-8761-b7b1f317bc81.png)

**Comment by YYHCOPPOLO** [comment]
收到，下次更新解决

**Comment by YYHCOPPOLO** [comment]
话说大纲线条我这里看是有的..

**Comment by Kitsuta-le** [comment]
> 话说大纲线条我这里看是有的..

啊是我搞错了，调了模式没调回去。是没问题的

**Comment by YYHCOPPOLO** [comment]
> > 话说大纲线条我这里看是有的..
> 
> 啊是我搞错了，调了模式没调回去。是没问题的

 按钮那些问题已经修复了，你可以直接下这个仓库的文件覆盖，因为D大部署时间也不固定
