### ISSUE TITLE
请问中文字体需要怎样设置？

### ISSUE THREAD

**Issue by wencaizhang** [YYHCOPPOLO/BluePrint-From-Tsundoku#3]
![image](https://user-images.githubusercontent.com/34718241/139679678-e60e9195-3f8b-4ba7-bb08-33bcba98c4cc.png)

如图，我使用主题后，和截图不一样啊，我是需要重新安装一个字体吗？

**Comment by YYHCOPPOLO** [comment]
截图中的字体为霞鹜文楷，下载地址：https://github.com/lxgw/LxgwWenKai ，安装后在思源-编辑器-字体就可以选择霞鹜文楷字体啦

**Comment by YYHCOPPOLO** [comment]
> ![image](https://user-images.githubusercontent.com/34718241/139679678-e60e9195-3f8b-4ba7-bb08-33bcba98c4cc.png)
> 
> 如图，我使用主题后，和截图不一样啊，我是需要重新安装一个字体吗？

截图中的字体为霞鹜文楷，下载地址：https://github.com/lxgw/LxgwWenKai ，安装后在思源-编辑器-字体就可以选择霞鹜文楷字体啦

**Comment by wencaizhang** [comment]
好的，这就去下载安装
