### ISSUE TITLE
列表下的代码样式问题

### ISSUE THREAD

**Issue by iswbm** [YYHCOPPOLO/BluePrint-From-Tsundoku#4]
Hi，请问下这个主题是从思源上下架了吗？

目前发现有个样式问题：https://github.com/siyuan-note/siyuan/issues/4282

有时间的话帮忙看看。感谢提供这么 nice 的主题，特别耐看！

**Comment by YYHCOPPOLO** [comment]
> 

之前考试没时间维护所以下架了，最近在改进，有什么建议可以一起提，我修改完会重新传回去的

**Comment by iswbm** [comment]
> 之前考试没时间维护所以下架了，最近在改进，有什么建议可以一起提，我修改完会重新传回去的

目前发现的问题是，在列表下继续使用代码框会有显示问题，如下图所示

<img width="804" alt="image" src="https://user-images.githubusercontent.com/22311419/158614109-2b6d0f5c-b9f6-4ea6-93c5-d792cdf23e25.png">

**Comment by YYHCOPPOLO** [comment]
> > 之前考试没时间维护所以下架了，最近在改进，有什么建议可以一起提，我修改完会重新传回去的
> 
> 目前发现的问题是，在列表下继续使用代码框会有显示问题，如下图所示
> 
> <img alt="image" width="804" src="https://user-images.githubusercontent.com/22311419/158614109-2b6d0f5c-b9f6-4ea6-93c5-d792cdf23e25.png">

这个已经修改完了，我再改改标题样式就重新上架

**Comment by YYHCOPPOLO** [comment]
> > 之前考试没时间维护所以下架了，最近在改进，有什么建议可以一起提，我修改完会重新传回去的
> 
> 目前发现的问题是，在列表下继续使用代码框会有显示问题，如下图所示
> 
> <img alt="image" width="804" src="https://user-images.githubusercontent.com/22311419/158614109-2b6d0f5c-b9f6-4ea6-93c5-d792cdf23e25.png">

我这边已经修改完毕了，你可以先自己下载着用用，集市那边好像有点问题，我问问在说

**Comment by iswbm** [comment]
好的，明天试一下。感谢~ 祝考试顺利
