### ISSUE TITLE
色调问题

### ISSUE THREAD

**Issue by cheyoo123** [YYHCOPPOLO/BluePrint-From-Tsundoku#5]
一级二级三级标题的颜色有些略浅
label如果改成透明浅蓝背景+深蓝绿的字可能会好看一些

**Comment by YYHCOPPOLO** [comment]
> 一级二级三级标题的颜色有些略浅 label如果改成透明浅蓝背景+深蓝绿的字可能会好看一些

深蓝绿是啥样的。。这个确实没get到

**Comment by cheyoo123** [comment]
> > 一级二级三级标题的颜色有些略浅 label如果改成透明浅蓝背景+深蓝绿的字可能会好看一些
> 
> 深蓝绿是啥样的。。这个确实没get到

大概是下面那样？主要是是背景浅色内容深色比背景深色字体白色和谐一点（以我使用的方式来看）主题本身就是蓝绿调的，所以说是深蓝绿色
![image](https://user-images.githubusercontent.com/60168002/160531059-4e506f65-aacd-4e30-b3b0-4f11151d4b02.png)
![69e20697279ff39528c4b5391a689f3](https://user-images.githubusercontent.com/60168002/160531085-0e7d6707-6287-4b9a-aaa0-ddf88aee5fab.png)

**Comment by YYHCOPPOLO** [comment]
> > > 一级二级三级标题的颜色有些略浅 label如果改成透明浅蓝背景+深蓝绿的字可能会好看一些
> > 
> > 
> > 深蓝绿是啥样的。。这个确实没get到
> 
> 大概是下面那样？主要是是背景浅色内容深色比背景深色字体白色和谐一点（以我使用的方式来看）主题本身就是蓝绿调的，所以说是深蓝绿色 ![image](https://user-images.githubusercontent.com/60168002/160531059-4e506f65-aacd-4e30-b3b0-4f11151d4b02.png) ![69e20697279ff39528c4b5391a689f3](https://user-images.githubusercontent.com/60168002/160531085-0e7d6707-6287-4b9a-aaa0-ddf88aee5fab.png)

噢噢可以的，我调一下
